### PR TITLE
RoR Capstone Project

### PR DESCRIPTION
**Pull request by mariordgez**
This project was intended to put my knowledge of Ruby on Rails module into practice through the Twitter-Redesign app that allows user to login, view homepage/tweets, suggestion on who to follow, access their user profile and those of others, and creating tweets.
I followed the MVP version of the app adding the following flow to the app
1. The user logs in to the app, only by typing the username (a proper authenticated login is **not** a requirement).
2. The user is presented with the homepage (see the *Homepage* screenshot above) that includes:
    1. Left-side menu (includes only links to pages that are implemented).
    2. *Tweets* tab in the centre (skip *Photos* and *Videos* for this MVP).
    3. Right-side section with *Who to follow (*skip *Trending for* this MVP).
3. The *Tweets* section includes:
    1. Simple form for creating a tweet.
    2. List of all tweets (sorted by most recent) that display tweet text and author details.
4. The *Who to follow* section includes:
    1. List of profiles that are not followed by the logged-in user (ordered by most recently added).
5. When the user opens the profile page (see the *Userpage* screenshot above), they can see:
    1. Left-side menu (includes only links to pages that are implemented).
    2. Cover picture and *Tweets* tab in the centre (skip other tabs and *Tweet to user* form).
    3. Right-side section with *Profile detailed info.*
6. The *Profile detailed info* section includes:
    1. User photo.
    2. Button to follow a user.
    3. Stats: total number of tweets, number of followers and number of following users.
    4. List of people who follow this user.
7. At the end extend your MVP app with one simple feature of your choice.

I added my own styling and design to a lot of parts of the page, but I was loyal to the layout and composition from the app, I hope that you enjoy this project and I hope to hear from all of you soon!

### CODE REVIEW

**Comment by mke2111** [comment]
Screenshot from 2021-07-27 11-46-35

**Comment by mariordgez** [comment]
Sorry for the inconvenience I forgot to update the link of the live demo, it has been updated now on the readme file, just in case I will share it here in the pull request as well: [Link](https://intense-river-89846.herokuapp.com)

**Comment by mariordgez** [comment]
I have all of the changes added to the master branch since the app has been deployed already, please check the master branch to view the most updated version of the app, thank you a lot for your time, have a nice day!

**Comment by mariordgez** [comment]
Here is a link to the new video where I explain some of the changes made to the app: [Video 2](https://www.loom.com/share/7364c5f353654c41af4bd4f56c735e30)

**Pull request merged**
